# Generated by Django 5.2.6 on 2025-09-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreasComunes',
            fields=[
                ('id', models.SmallAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('costo', models.DecimalField(blank=True, db_column='Costo', decimal_places=2, max_digits=12, null=True)),
                ('capacidad_max', models.SmallIntegerField(blank=True, db_column='CapacidadMax', null=True)),
                ('estado', models.TextField(blank=True, db_column='Estado', null=True)),
            ],
            options={
                'db_table': 'AreasComunes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('fecha_ini', models.DateField(blank=True, db_column='FechaIni', null=True)),
                ('fecha_fin', models.DateField(blank=True, db_column='FechaFin', null=True)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('costo', models.DecimalField(blank=True, db_column='Costo', decimal_places=2, max_digits=12, null=True)),
                ('dificultades', models.TextField(blank=True, db_column='Dificultades', null=True)),
                ('estado', models.TextField(blank=True, db_column='Estado', null=True)),
            ],
            options={
                'db_table': 'Asignacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('ip', models.TextField(blank=True, db_column='IP', null=True)),
                ('accion', models.TextField(blank=True, db_column='Accion', null=True)),
                ('fecha', models.DateField(blank=True, db_column='Fecha', null=True)),
                ('hora', models.TimeField(blank=True, db_column='Hora', null=True)),
            ],
            options={
                'db_table': 'Bitacora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comunicados',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('tipo', models.TextField(blank=True, db_column='Tipo', null=True)),
                ('fecha', models.DateField(blank=True, db_column='Fecha', null=True)),
                ('hora', models.TimeField(blank=True, db_column='Hora', null=True)),
                ('titulo', models.TextField(blank=True, db_column='Titulo', null=True)),
                ('contenido', models.TextField(blank=True, db_column='Contenido', null=True)),
                ('url', models.TextField(blank=True, db_column='Url', null=True)),
                ('estado', models.TextField(blank=True, db_column='Estado', null=True)),
            ],
            options={
                'db_table': 'Comunicados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleMulta',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('fecha_emi', models.DateField(blank=True, db_column='FechaEmi', null=True)),
                ('fecha_lim', models.DateField(blank=True, db_column='FechaLim', null=True)),
            ],
            options={
                'db_table': 'DetalleMulta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, db_column='Fecha', null=True)),
                ('hora', models.TimeField(blank=True, db_column='Hora', null=True)),
                ('estado', models.TextField(blank=True, db_column='Estado', null=True)),
            ],
            options={
                'db_table': 'Envio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, db_column='Fecha', null=True)),
                ('hora', models.TimeField(blank=True, db_column='Hora', null=True)),
                ('tipo_pago', models.TextField(blank=True, db_column='TipoPago', null=True)),
                ('estado', models.TextField(blank=True, db_column='Estado', null=True)),
            ],
            options={
                'db_table': 'Factura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Finanzas',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('tipo', models.TextField(blank=True, db_column='Tipo', null=True)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('monto', models.DecimalField(blank=True, db_column='Monto', decimal_places=2, max_digits=12, null=True)),
                ('fecha', models.DateField(blank=True, db_column='Fecha', null=True)),
                ('origen', models.TextField(blank=True, db_column='Origen', null=True)),
            ],
            options={
                'db_table': 'Finanzas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.SmallAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('hora_ini', models.TimeField(blank=True, db_column='HoraIni', null=True)),
                ('hora_fin', models.TimeField(blank=True, db_column='HoraFin', null=True)),
            ],
            options={
                'db_table': 'Horarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListaVisitantes',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True, db_column='Nombre', null=True)),
                ('apellido', models.TextField(blank=True, db_column='Apellido', null=True)),
                ('carnet', models.TextField(blank=True, db_column='Carnet', null=True)),
                ('motivo_visita', models.TextField(blank=True, db_column='MotivoVisita', null=True)),
                ('fecha_ini', models.DateField(blank=True, db_column='FechaIni', null=True)),
                ('fecha_fin', models.DateField(blank=True, db_column='FechaFin', null=True)),
            ],
            options={
                'db_table': 'ListaVisitantes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.SmallAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('monto', models.DecimalField(blank=True, db_column='Monto', decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'Multa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.SmallAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('tipo', models.TextField(blank=True, db_column='Tipo', null=True)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
            ],
            options={
                'db_table': 'Notificaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.SmallAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('tipo', models.TextField(blank=True, db_column='Tipo', null=True)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('monto', models.DecimalField(blank=True, db_column='Monto', decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'Pagos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pertenece',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('fecha_ini', models.DateField(blank=True, db_column='FechaIni', null=True)),
                ('fecha_fin', models.DateField(blank=True, db_column='FechaFin', null=True)),
            ],
            options={
                'db_table': 'Pertenece',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('codigo', models.SmallAutoField(db_column='Codigo', primary_key=True, serialize=False)),
                ('tamano_m2', models.DecimalField(blank=True, db_column='Tamano m2', decimal_places=2, max_digits=12, null=True)),
                ('nro_casa', models.SmallIntegerField(blank=True, db_column='NroCasa', null=True)),
                ('piso', models.SmallIntegerField(blank=True, db_column='Piso', null=True)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
            ],
            options={
                'db_table': 'Propiedad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, db_column='Fecha', null=True)),
                ('hora', models.TimeField(blank=True, db_column='Hora', null=True)),
            ],
            options={
                'db_table': 'Registro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, db_column='Fecha', null=True)),
                ('estado', models.TextField(blank=True, db_column='Estado', null=True)),
            ],
            options={
                'db_table': 'Reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.SmallAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('tipo', models.TextField(blank=True, db_column='Tipo', null=True)),
                ('estado', models.TextField(blank=True, db_column='Estado', null=True)),
            ],
            options={
                'db_table': 'Rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.SmallAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('tipo', models.TextField(blank=True, db_column='Tipo', null=True)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('costos', models.DecimalField(blank=True, db_column='Costos', decimal_places=2, max_digits=12, null=True)),
                ('vigencia', models.SmallIntegerField(blank=True, db_column='Vigencia', null=True)),
            ],
            options={
                'db_table': 'Tareas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('codigo', models.BigAutoField(db_column='Codigo', primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True, db_column='Nombre', null=True)),
                ('apellido', models.TextField(blank=True, db_column='Apellido', null=True)),
                ('correo', models.TextField(blank=True, db_column='Correo', null=True)),
                ('contrasena', models.TextField(blank=True, db_column='Contrasena', null=True)),
                ('sexo', models.TextField(blank=True, db_column='Sexo', null=True)),
                ('telefono', models.IntegerField(blank=True, db_column='Telefono', null=True)),
                ('estado', models.TextField(blank=True, db_column='Estado', null=True)),
            ],
            options={
                'db_table': 'Usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nro_placa', models.TextField(blank=True, db_column='NroPlaca', null=True)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('estado', models.TextField(blank=True, db_column='Estado', null=True)),
            ],
            options={
                'db_table': 'Vehiculo',
                'managed': False,
            },
        ),
    ]
