# Generated by Django 5.2.6 on 2025-09-21 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeteccionPlaca',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('placa_detectada', models.TextField(db_column='PlacaDetectada')),
                ('imagen_path', models.TextField(blank=True, db_column='ImagenPath', null=True)),
                ('imagen_url', models.URLField(blank=True, db_column='ImagenUrl', null=True)),
                ('confianza', models.DecimalField(db_column='Confianza', decimal_places=2, max_digits=5)),
                ('es_autorizado', models.BooleanField(db_column='EsAutorizado', default=False)),
                ('fecha_deteccion', models.DateTimeField(auto_now_add=True, db_column='FechaDeteccion')),
                ('ubicacion_camara', models.TextField(blank=True, db_column='UbicacionCamara', null=True)),
                ('tipo_acceso', models.TextField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], db_column='TipoAcceso')),
                ('vehiculo', models.ForeignKey(blank=True, db_column='IdVehiculo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detecciones', to='api.vehiculo')),
            ],
            options={
                'db_table': 'DeteccionPlaca',
            },
        ),
        migrations.CreateModel(
            name='PerfilFacial',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('encoding_facial', models.TextField(db_column='EncodingFacial')),
                ('imagen_path', models.TextField(blank=True, db_column='ImagenPath', null=True)),
                ('imagen_url', models.URLField(blank=True, db_column='ImagenUrl', null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='FechaRegistro')),
                ('activo', models.BooleanField(db_column='Activo', default=True)),
                ('codigo_usuario', models.OneToOneField(db_column='CodigoUsuario', on_delete=django.db.models.deletion.CASCADE, related_name='perfil_facial', to='api.usuario')),
            ],
            options={
                'db_table': 'PerfilFacial',
            },
        ),
        migrations.CreateModel(
            name='ReconocimientoFacial',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('imagen_path', models.TextField(blank=True, db_column='ImagenPath', null=True)),
                ('imagen_url', models.URLField(blank=True, db_column='ImagenUrl', null=True)),
                ('confianza', models.DecimalField(db_column='Confianza', decimal_places=2, max_digits=5)),
                ('es_residente', models.BooleanField(db_column='EsResidente', default=False)),
                ('fecha_deteccion', models.DateTimeField(auto_now_add=True, db_column='FechaDeteccion')),
                ('ubicacion_camara', models.TextField(blank=True, db_column='UbicacionCamara', null=True)),
                ('estado', models.TextField(choices=[('permitido', 'Permitido'), ('denegado', 'Denegado'), ('revision', 'En Revisión')], db_column='Estado', default='revision')),
                ('codigo_usuario', models.ForeignKey(blank=True, db_column='CodigoUsuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconocimientos', to='api.usuario')),
            ],
            options={
                'db_table': 'ReconocimientoFacial',
            },
        ),
        migrations.CreateModel(
            name='ReporteSeguridad',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('tipo_evento', models.TextField(choices=[('acceso_facial', 'Acceso Facial'), ('acceso_vehicular', 'Acceso Vehicular'), ('intruso_detectado', 'Intruso Detectado'), ('placa_no_autorizada', 'Placa No Autorizada')], db_column='TipoEvento')),
                ('descripcion', models.TextField(db_column='Descripcion')),
                ('nivel_alerta', models.TextField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('critico', 'Crítico')], db_column='NivelAlerta', default='medio')),
                ('fecha_evento', models.DateTimeField(auto_now_add=True, db_column='FechaEvento')),
                ('revisado', models.BooleanField(db_column='Revisado', default=False)),
                ('deteccion_placa', models.ForeignKey(blank=True, db_column='IdDeteccionPlaca', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes', to='api.deteccionplaca')),
                ('reconocimiento_facial', models.ForeignKey(blank=True, db_column='IdReconocimientoFacial', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes', to='api.reconocimientofacial')),
                ('revisor', models.ForeignKey(blank=True, db_column='CodigoRevisor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_revisados', to='api.usuario')),
            ],
            options={
                'db_table': 'ReporteSeguridad',
                'ordering': ['-fecha_evento'],
            },
        ),
    ]
